#配置端口
server:
  port: 10086
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ihouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  cache:
#    type: redis
#    cache-names: rediesCache
#  redis:
#    host: 182.92.196.229
#    port: 6379
#    timeout: 1000
#    #使用jedis操作redis 配置jedis连接池
#    jedis:
#      pool:
#        max-active: 10
#        max-wait: -1
#        max-idle: 8
#        min-idle: 5
#mybatis-plus的配置
#xml映射文件 扫描的基础目录  多个目录之间使用逗号分隔
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #可选配置
  global-config:
    db-config:
      #主键类型
      id-type: auto
      table-underline: true
      table-prefix: tb_
  configuration:
    #将下划线转换为驼峰命名法
    map-underscore-to-camel-case: true
    #对空值列的映射配置
    call-setters-on-nulls: true
    #在开发阶段 将执行的sql打印出来
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl